"""Synthetic fixtures generated by the application; never represent actual businesses."""

from pathlib import Path
from openpyxl import Workbook


def create_demo(directory: str | Path) -> list[Path]:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    paths = [directory / "01_корректный.xlsx", directory / "02_ошибки.xlsx", directory / "03_другие_столбцы.csv"]
    if any(path.exists() for path in paths):
        raise ValueError("Демо-файлы уже существуют. Выберите другую папку.")
    for path, broken in zip(paths[:2], (False, True)):
        wb = Workbook()
        ws = wb.active
        ws.title = "Реестр"
        ws.append(["СИНТЕТИЧЕСКИЕ ДАННЫЕ — не реальные организации и операции"])
        ws.append([])
        ws.append(["Дата", "Документ", "БИН", "Наименование", "Сумма платежа", "Код валюты", "Назначение", "Внутренняя пометка"])
        ws.append(["01.10.2026", "0001", "001234567890", "Учебный контрагент А", "125 000,50", "KZT", "Учебная поставка", "Не входит в шаблон"])
        ws.append(["2026-10-02", "0002", "009876543210", "Учебный контрагент Б", 4500, "KZT", "Учебная услуга", None])
        ws.append(["03.10.2026", "0003", "000000000001", "Учебный контрагент В", "-250,00", "KZT", "Учебный возврат", None])
        if broken:
            ws.append(["04/05/2026", "0004", "12345", "Учебный контрагент Г", "1,234", "тенге", None])
            ws.append(["05.10.2026", "0005", "000000000002", "Учебный контрагент Д", "=100+200", "KZT", "Формула требует проверки"])
            ws.append(["ИТОГО", None, None, None, 129550.50])
        ws.freeze_panes = "A4"
        for letter, width in {"A": 24, "B": 20, "C": 20, "D": 32, "E": 22, "F": 20, "G": 32, "H": 30}.items():
            ws.column_dimensions[letter].width = width
        with path.open("xb") as stream:
            wb.save(stream)
        wb.close()
    with paths[2].open("x", encoding="utf-8-sig", newline="") as stream:
        stream.write('Получатель;БИН контрагента;Дата платежа;№ документа;Валюта;Сумма операции;Комментарий\n')
        stream.write('Учебный контрагент А;001234567890;01.10.2026;0001;KZT;125000,50;Учебная поставка\n')
    return paths
