"""Desktop layout: a guided workflow with an immediately usable demo start screen."""
import tkinter as tk
from tkinter import ttk
from .dpi import fit_window, px


def build(app):
    root = app.root
    root.title('Excel Converter · подготовка данных')
    fit_window(root, 1220, 850, 1020, 720)
    style = ttk.Style()
    if 'clam' in style.theme_names():
        style.theme_use('clam')
    bg, ink, muted, blue = '#f3f6fa', '#152b43', '#52657a', '#2463eb'
    style.configure('.', font=('Segoe UI', 10))
    style.configure('TFrame', background=bg)
    style.configure('TLabel', background=bg, foreground=ink)
    style.configure('Title.TLabel', font=('Segoe UI', 23, 'bold'))
    style.configure('Heading.TLabel', font=('Segoe UI', 17, 'bold'))
    style.configure('Muted.TLabel', foreground=muted)
    style.configure('Card.TFrame', background='white', relief='solid', borderwidth=1)
    style.configure('Card.TLabel', background='white', foreground=ink)
    style.configure('CardTitle.TLabel', background='white', font=('Segoe UI', 13, 'bold'))
    style.configure('Metric.TLabel', background='white', foreground=blue, font=('Segoe UI', 24, 'bold'))
    style.configure('TButton', padding=(12, 8))
    style.configure('Primary.TButton', background=blue, foreground='white', font=('Segoe UI', 10, 'bold'))
    style.map('Primary.TButton', background=[('disabled', '#dce3ed'), ('active', '#174cbd')], foreground=[('disabled', '#738197')])
    style.configure('Treeview', rowheight=29, background='white', fieldbackground='white', foreground=ink)
    style.configure('Treeview.Heading', font=('Segoe UI', 10, 'bold'), padding=8)
    style.configure('TNotebook', background=bg, borderwidth=0)
    style.configure('TNotebook.Tab', padding=(16, 11))
    style.map('TNotebook.Tab', background=[('selected', 'white')], foreground=[('selected', blue)])
    header = ttk.Frame(app)
    header.pack(fill='x', pady=(0, 12))
    ttk.Label(header, text='Excel Converter', style='Title.TLabel').pack(side='left')
    ttk.Label(header, text='Локальная обработка  ·  Исходник остаётся целым', style='Muted.TLabel').pack(side='left', padx=22)
    ttk.Button(header, text='На весь экран · F11', command=app.toggle_fullscreen).pack(side='right')
    app.notebook = ttk.Notebook(app)
    # Reserve the footer first so it cannot be pushed below the window by tables.
    footer = ttk.Frame(app)
    footer.pack(side='bottom', fill='x', pady=(12, 0))
    app.status_label = ttk.Label(footer, textvariable=app.status, wraplength=1120, style='Muted.TLabel')
    app.status_label.pack(anchor='w', pady=(7, 0), side='bottom')
    app.progress = ttk.Progressbar(footer, mode='indeterminate', length=120)
    app.progress.pack(side='right', padx=8)
    app.check_button = ttk.Button(footer, text='Проверить данные · F5', style='Primary.TButton', command=app.check)
    app.check_button.pack(side='left')
    app.export_button = ttk.Button(footer, text='Сохранить Excel', style='Primary.TButton', command=app.export, state='disabled')
    app.export_button.pack(side='left', padx=8)
    app.report_button = ttk.Button(footer, text='Отчёт проверки', command=app.save_report, state='disabled')
    app.report_button.pack(side='left')
    app.notebook.pack(fill='both', expand=True)
    app.home_tab = ttk.Frame(app.notebook, padding=22)
    app.source_tab = ttk.Frame(app.notebook, padding=16)
    app.mapping_tab = ttk.Frame(app.notebook, padding=16)
    app.issues_tab = ttk.Frame(app.notebook, padding=16)
    app.result_tab = ttk.Frame(app.notebook, padding=16)
    for frame, title in [(app.home_tab, 'Старт и демо'), (app.source_tab, '1  Исходный файл'), (app.mapping_tab, '2  Столбцы и правила'), (app.issues_tab, '3  Проверка'), (app.result_tab, '4  Результат')]:
        app.notebook.add(frame, text=title)
    home = app.home_tab
    ttk.Label(home, text='Подготовьте таблицу к загрузке в систему', style='Heading.TLabel').pack(anchor='w')
    ttk.Label(home, text='Откройте файл → проверьте столбцы → исправьте замечания → сохраните результат.', style='Muted.TLabel').pack(anchor='w', pady=(8, 18))
    app.open_button = ttk.Button(home, text='Открыть свой Excel или CSV…', style='Primary.TButton', command=app.open_file)
    app.open_button.pack(anchor='w', pady=(0, 24))
    ttk.Label(home, text='Попробуйте без подготовки файлов', style='Heading.TLabel').pack(anchor='w')
    ttk.Label(home, text='Все примеры синтетические. Демо запускается сразу и не требует Excel.', style='Muted.TLabel').pack(anchor='w', pady=(6, 14))
    cards = ttk.Frame(home)
    cards.pack(fill='x')
    app.demo_buttons = []
    scenarios = [
        ('formats', '01  Разные форматы', 'Даты, суммы и валюты записаны по-разному. Посмотрите, как они приводятся к единому виду.', 'Запустить преобразование'),
        ('errors', '02  Исправление ошибок', 'Три неоднозначные ячейки. Исправьте их вручную или примените подготовленные учебные значения.', 'Показать ошибки'),
        ('csv', '03  Другая структура', 'CSV с переставленными столбцами. Программа находит нужные поля по названиям.', 'Открыть CSV-пример'),
    ]
    for column, (key, title, description, label) in enumerate(scenarios):
        cards.columnconfigure(column, weight=1, uniform='cards')
        card = ttk.Frame(cards, padding=16, style='Card.TFrame')
        card.grid(row=0, column=column, sticky='nsew', padx=(0, 12 if column < 2 else 0))
        ttk.Label(card, text=title, style='CardTitle.TLabel').pack(anchor='w')
        text = ttk.Label(card, text=description, style='Card.TLabel', wraplength=285)
        text.pack(anchor='w', fill='x', pady=15)
        card.bind('<Configure>', lambda event, label=text: label.configure(wraplength=max(px(root, 180), event.width - px(root, 36))))
        button = ttk.Button(card, text=label, command=lambda k=key: app.start_demo(k))
        button.pack(side='bottom', anchor='w', pady=(4, 0))
        app.demo_buttons.append(button)
    app.demo_button = ttk.Button(home, text='Сохранить учебные файлы в папку…', command=app.make_demo)
    app.demo_button.pack(anchor='w', pady=(18, 10))
    ttk.Label(home, text='Демонстрационный формат. Совместимость с системой департамента ещё не проверена.', style='Muted.TLabel', wraplength=1000).pack(anchor='w')

    ttk.Label(app.source_tab, text='Проверьте, откуда брать данные', style='Heading.TLabel').pack(anchor='w')
    filebar = ttk.Frame(app.source_tab)
    filebar.pack(fill='x', pady=10)
    ttk.Label(filebar, textvariable=app.filename, wraplength=850).pack(side='left')
    app.other_file_button = ttk.Button(filebar, text='Другой файл…', command=app.open_file)
    app.other_file_button.pack(side='right')
    controls = ttk.Frame(app.source_tab)
    controls.pack(fill='x', pady=(0, 10))
    ttk.Label(controls, text='Лист').pack(side='left')
    app.sheet_box = ttk.Combobox(controls, textvariable=app.sheet_var, state='readonly', width=23)
    app.sheet_box.pack(side='left', padx=8)
    app.sheet_box.bind('<<ComboboxSelected>>', lambda _: app.select_sheet())
    ttk.Label(controls, text='Строка с названиями столбцов').pack(side='left', padx=(15, 5))
    app.header_entry = ttk.Entry(controls, textvariable=app.header_var, width=5)
    app.header_entry.pack(side='left')
    app.mapping_button = ttk.Button(controls, text='Применить', command=app.apply_headers)
    app.mapping_button.pack(side='left', padx=8)
    app.next_button = ttk.Button(controls, text='Далее: столбцы →', command=lambda: app.notebook.select(app.mapping_tab))
    app.next_button.pack(side='right')
    ttk.Label(app.source_tab, text='Показаны первые 200 строк. Номер слева — строка исходного файла.', style='Muted.TLabel').pack(anchor='w', pady=(0, 8))
    app.source_tree = app.make_tree(app.source_tab)

    ttk.Label(app.mapping_tab, text='Как исходные столбцы попадут в результат', style='Heading.TLabel').pack(anchor='w')
    profilebar = ttk.Frame(app.mapping_tab)
    profilebar.pack(fill='x', pady=10)
    app.profile_button = ttk.Button(profilebar, text='Загрузить профиль…', command=app.open_profile)
    app.profile_button.pack(side='left')
    app.save_profile_button = ttk.Button(profilebar, text='Запомнить настройки…', command=app.save_profile)
    app.save_profile_button.pack(side='left', padx=8)
    ttk.Label(app.mapping_tab, textvariable=app.profile_label, wraplength=1100, style='Muted.TLabel').pack(anchor='w', pady=(0, 10))
    parsing = ttk.Frame(app.mapping_tab)
    parsing.pack(fill='x', pady=(0, 8))
    ttk.Label(parsing, text='Даты').pack(side='left')
    app.date_order = tk.StringVar(value='Авто')
    app.date_order_box = ttk.Combobox(parsing, textvariable=app.date_order, values=['Авто', 'День–месяц–год', 'Месяц–день–год'], state='readonly', width=19)
    app.date_order_box.pack(side='left', padx=8)
    ttk.Label(parsing, text='Десятичный разделитель').pack(side='left')
    app.decimal_separator = tk.StringVar(value='Авто')
    app.decimal_box = ttk.Combobox(parsing, textvariable=app.decimal_separator, values=['Авто', 'Точка', 'Запятая'], state='readonly', width=10)
    app.decimal_box.pack(side='left', padx=8)
    app.drop_time = tk.BooleanVar(value=False)
    app.time_check = ttk.Checkbutton(parsing, text='Отбрасывать время', variable=app.drop_time, command=app.parsing_changed)
    app.time_check.pack(side='left', padx=8)
    for box in (app.date_order_box, app.decimal_box):
        box.bind('<<ComboboxSelected>>', lambda _: app.parsing_changed())
    ttk.Label(app.mapping_tab, text='Обычно достаточно «Авто». Звёздочка обозначает обязательное поле.', style='Muted.TLabel').pack(anchor='w', pady=(0, 8))
    canvas_frame = ttk.Frame(app.mapping_tab)
    canvas_frame.pack(fill='both', expand=True)
    app.mapping_canvas = tk.Canvas(canvas_frame, highlightthickness=0, background=bg)
    scroll = ttk.Scrollbar(canvas_frame, orient='vertical', command=app.mapping_canvas.yview)
    app.mapping_canvas.configure(yscrollcommand=scroll.set)
    scroll.pack(side='right', fill='y')
    app.mapping_canvas.pack(side='left', fill='both', expand=True)
    app.mapping_frame = ttk.Frame(app.mapping_canvas)
    app.mapping_canvas.create_window((0, 0), window=app.mapping_frame, anchor='nw')
    app.mapping_frame.bind('<Configure>', lambda _: app.mapping_canvas.configure(scrollregion=app.mapping_canvas.bbox('all')))

    ttk.Label(app.issues_tab, text='Что требует вашего внимания', style='Heading.TLabel').pack(anchor='w')
    app.check_hint = tk.StringVar(value='Загрузите файл и нажмите «Проверить данные».')
    ttk.Label(app.issues_tab, textvariable=app.check_hint, wraplength=1100, style='Muted.TLabel').pack(anchor='w', pady=10)
    actions = ttk.Frame(app.issues_tab)
    actions.pack(fill='x', pady=(0, 10))
    app.fix_button = ttk.Button(actions, text='Исправить ошибочные ячейки…', style='Primary.TButton', command=app.edit_errors, state='disabled')
    app.fix_button.pack(side='left')
    app.demo_fix_button = ttk.Button(actions, text='Применить учебные исправления', command=app.fix_demo, state='disabled')
    app.demo_fix_button.pack(side='left', padx=8)
    app.issues_tree = app.make_tree(app.issues_tab)
    app.issues_tree.bind('<Double-1>', app.show_issue)
    app.issues_tree.tag_configure('error', background='#fff0f0', foreground='#9a2222')
    app.issues_tree.tag_configure('warning', background='#fff8e7', foreground='#795212')

    ttk.Label(app.result_tab, text='Результат преобразования', style='Heading.TLabel').pack(anchor='w')
    metrics = ttk.Frame(app.result_tab)
    metrics.pack(fill='x', pady=12)
    app.metric_vars = []
    for col, label in enumerate(['Записей прочитано', 'Корректных записей', 'Ошибок', 'Изменений значений']):
        metrics.columnconfigure(col, weight=1, uniform='metric')
        card = ttk.Frame(metrics, padding=12, style='Card.TFrame')
        card.grid(row=0, column=col, sticky='ew', padx=(0, 8))
        value = tk.StringVar(value='—')
        app.metric_vars.append(value)
        ttk.Label(card, textvariable=value, style='Metric.TLabel').pack(anchor='w')
        ttk.Label(card, text=label, style='Card.TLabel').pack(anchor='w')
    app.summary = tk.StringVar(value='Здесь появятся готовые данные и список изменений.')
    ttk.Label(app.result_tab, textvariable=app.summary, wraplength=1100, style='Muted.TLabel').pack(anchor='w', pady=(0, 8))
    sub = ttk.Notebook(app.result_tab)
    sub.pack(fill='both', expand=True)
    data, changes = ttk.Frame(sub, padding=6), ttk.Frame(sub, padding=6)
    sub.add(data, text='Готовая таблица')
    sub.add(changes, text='Было → стало')
    app.result_tree = app.make_tree(data)
    app.changes_tree = app.make_tree(changes)
    root.bind('<Control-o>', lambda _: app.open_file() if not app.busy else None)
    root.bind('<F5>', lambda _: app.check() if app.source and not app.busy else None)
    root.bind('<Control-s>', lambda _: app.export() if not app.busy else None)
    root.bind('<F11>', lambda _: app.toggle_fullscreen())
    root.bind('<Escape>', lambda _: root.attributes('-fullscreen', False))
    app.set_busy(False)
